### PR TITLE
Common Fixes, Missing Configuration and Family History Section Parsing

### PR DESCRIPTION
**Pull request by kushalvermaecw**
- Fix to avoid NullPointerException for lineNumbers during Test (ApplicationUtil.java)
- Fix for failing parser if XML contains Special Characters like degree symbol (PositionalXMLReader.java)
- Adding Spring Configuration for Component Scan (CCDAParsingAPIConfiguration.java)
- Fixing main class in RunParser.java and initialize CCDAParserAPI with context bean

### CODE REVIEW

**Comment by kushalvermaecw** [comment]
@drbgfc, @monikadrajer, @Plow74, @nbashyam 

Can you review this Pull Request?

**Comment by drbgfc** [comment]
I will review by next week at the latest, thanks. If someone else can get to it sooner, please do so.

**Comment by kushalvermaecw** [comment]
> I will review by next week at the latest, thanks. If someone else can get to it sooner, please do so.

**Comment by drbgfc** [comment]
I still have my eye on this - sorry, have been busy with other work. I will likely merge into a new public develop branch to epedite so that we can take time testing before merging to master. We should have a develop branch anyway.

**Pull request merged**
